included:
  - Sources
excluded:
  - Resources
  - .build
  - .github

analyzer_rules:
  - unused_import

opt_in_rules:
  - empty_count
  - explicit_init
  - implicit_return
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_type_annotation

disabled_rules:
  - orphaned_doc_comment

identifier_name:
  min_length: 2
  excluded: [x, y, t, i, j, m, v, dp, ca]

line_length:
  warning: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300

file_length:
  warning: 800

cyclomatic_complexity:
  warning: 15

function_parameter_count:
  warning: 6

nesting:
  type_level:
    warning: 2

reporter: xcode

