name: Caligraphy
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.9
packages: {}

schemes:
  Caligraphy:
    build:
      targets:
        Caligraphy: all
    run:
      config: Debug
      executable: Caligraphy
      askForAppToLaunch: false
      launchAutomaticallySubstyle: 2
    test:
      config: Debug
      gatherCoverageData: false
    profile:
      config: Release
      executable: Caligraphy
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true

targets:
  Caligraphy:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.julio.Caligraphy
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9H7MCGU89J
        CODE_SIGN_IDENTITY: Apple Development
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    postbuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint >/dev/null; then swiftlint; else echo "SwiftLint not installed"; fi
  CaligraphyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/CaligraphyTests
    dependencies:
      - target: Caligraphy
    settings:
      base:
        TEST_HOST: ""
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9H7MCGU89J
        CODE_SIGN_IDENTITY: Apple Development
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
